name: Build and Test Feature Branch

on:
  push:
    branches: [ feature/code-improvements ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests (if any)
        run: npm test --if-present

      - name: Build project for feature branch
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}

      - name: Create feature branch info
        run: |
          # Create a README for the build
          cat > ./dist/README.md << 'EOF'
          # 🚀 Feature Branch Build - Code Improvements
          
          ## Point 1: Component Optimization - COMPLETED
          
          ### ✨ What's New in This Branch:
          - **Custom Hooks:** useShoppingLists, useListOperations, useModals
          - **New Components:** ListCard, Navigation
          - **App.jsx Refactoring:** 28% reduction in complexity (1252 → 903 lines)
          - **Better Code Organization:** Separation of concerns and reusability
          - **Performance Improvements:** Optimized re-renders and bundle size
          
          ### 🧪 Testing Instructions:
          1. Download this artifact from GitHub Actions
          2. Extract the files
          3. Serve the files using a local server:
             ```bash
             # Using Python
             python -m http.server 8000
             
             # Using Node.js
             npx serve .
             
             # Using PHP
             php -S localhost:8000
             ```
          4. Navigate to `http://localhost:8000/boodschappen-lijst/`
          5. Test all functionality to verify no regressions
          
          ### 📊 Build Info:
          - Branch: feature/code-improvements
          - Build Date: $(date)
          - Status: Ready for Testing
          - Next Step: Point 2 - Error Handling Enhancement
          EOF

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: feature-branch-build
          path: ./dist
          retention-days: 30

      - name: Create deployment summary
        run: |
          echo "## 🚀 Feature Branch Build Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### ✅ Build Status: SUCCESS" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📦 Artifact Information:" >> $GITHUB_STEP_SUMMARY
          echo "- **Name:** feature-branch-build" >> $GITHUB_STEP_SUMMARY
          echo "- **Size:** $(du -sh ./dist | cut -f1)" >> $GITHUB_STEP_SUMMARY
          echo "- **Files:** $(find ./dist -type f | wc -l) files" >> $GITHUB_STEP_SUMMARY
          echo "- **Retention:** 30 days" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🧪 Testing Instructions:" >> $GITHUB_STEP_SUMMARY
          echo "1. Download the artifact from this workflow run" >> $GITHUB_STEP_SUMMARY
          echo "2. Extract and serve locally using \`npx serve .\`" >> $GITHUB_STEP_SUMMARY
          echo "3. Navigate to \`http://localhost:3000/boodschappen-lijst/\`" >> $GITHUB_STEP_SUMMARY
          echo "4. Test all functionality to verify no regressions" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🎯 What's New:" >> $GITHUB_STEP_SUMMARY
          echo "- Custom Hooks: useShoppingLists, useListOperations, useModals" >> $GITHUB_STEP_SUMMARY
          echo "- New Components: ListCard, Navigation" >> $GITHUB_STEP_SUMMARY
          echo "- App.jsx reduced by 28% (1252 → 903 lines)" >> $GITHUB_STEP_SUMMARY
          echo "- Better code organization and maintainability" >> $GITHUB_STEP_SUMMARY